# Generated by Django 4.1.7 on 2023-03-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('picture_location', models.CharField(max_length=256)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
